#ifndef __MEVENT_TRACE_H__
#define __MEVENT_TRACE_H__

#define PREFIX_TRACE     "Trace"

enum {
    TRACE_TYPE_PAGEVIEW = 0,

    TRACE_TYPE_PLAN_SEARCH = 11,
    TRACE_TYPE_PLAN_BOSH,
    TRACE_TYPE_PLAN_LEAVE,
    TRACE_TYPE_PLAN_SPD,
    TRACE_TYPE_PLAN_EXPECT,
    TRACE_TYPE_PLAN_MEET,

    TRACE_TYPE_MEMBER_REG = 51,
    TRACE_TYPE_MEMBER_LOGIN,
    TRACE_TYPE_MEMBER_MSG,

    TRACE_TYPE_BORE_COMMENT = 71
};

enum {
    REQ_CMD_TRACE_GET = 1001,
    REQ_CMD_TRACE_ADD
};

#endif    /* __MEVENT_TRACE_H__ */
